const ProjectsData = [
    {
        id: 1,
        name: "Blog",
        description: "自己独立开发的博客项目",
        gitUrl:"https://github.com",
        homeUrl:"https://github.com",
        cover:"https://github.com",
    },
    {
        id: 2,
        name: "spdDB",
        description: "轻量级，快速的关系型数据库",
        gitUrl:"https://github.com",
        homeUrl:"https://github.com",
        cover:"https://github.com",
    },
    {
        id: 3,
        name: "pureland",
        description: "净土，烂尾项目",
        gitUrl:"https://github.com",
        homeUrl:"https://github.com",
        cover:"https://github.com",
    },
    {
        id: 4,
        name: "Check My IP Address",
        description: "查看你的ip地址，本地dns解析设置",
        gitUrl:"https://github.com",
        homeUrl:"https://github.com",
        cover:"https://github.com",
    },
    {
        id: 5,
        name: "Blog",
        description: "自己独立开发的博客项目",
        gitUrl:"https://github.com",
        homeUrl:"https://github.com",
        cover:"https://github.com",
    },
    {
        id: 6,
        name: "Blog",
        description: "自己独立开发的博客项目",
        gitUrl:"https://github.com",
        homeUrl:"https://github.com",
        cover:"https://github.com",
    },
]
export default ProjectsData;